// ─────────────────────────────────────────────────────────────
// syndrome_registry 数据分片：syndrome_registry_p1.dart（R-019 ≤300 行）
// 逐字迁移自 syndrome_registry.dart，零行为变更。
// ─────────────────────────────────────────────────────────────
part of 'syndrome_registry.dart';

/// kSyndromeRegistry 数据段（P003-P015，13 条）
const List<SyndromeRecord> _syndromeRegistryP1 = [
  // ── L1 基础表达 ──────────────────────────────────────────
  SyndromeRecord(
    id: 'P003',
    name: '情绪标签化',
    shortName: '情绪标签化',
    keyword: '情绪词替代描写',
    oneLine: '用"愤怒/悲伤/害怕"等词直接告知情绪，无具体感官细节',
    typeLine: '描写缺乏细节',
    trainingLine: '用情绪词替代具体感官描写，读者被"告知"而非"感受到"',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l1,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T001', 'T002', 'T020', 'T031'],
    actions: ['A004', 'A006'],
  ),
  SyndromeRecord(
    id: 'P004',
    name: '信息倾泻症（含原 P001 世界观膨胀子类型）',
    shortName: '信息倾泻症',
    keyword: '设定信息旁白交代',
    oneLine: '世界观/背景以说明书方式直接陈述，非嵌在场景中',
    typeLine: '信息呈现方式不当',
    trainingLine: '设定以旁白方式直接交代，读者被"暂停故事"来学设定',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.structure,
    position: 'beginning',
    techniques: ['T010', 'T011'],
    actions: ['A002', 'A008'],
    v1ActionName: '信息倾泻症（含原 P001 子类型）',
    v2ActionName: '信息倾泻',
  ),
  SyndromeRecord(
    id: 'P005',
    name: '视角漂移',
    shortName: '视角漂移',
    keyword: '视角越界',
    oneLine: '写了当前视角角色看不到/听不到/不知道的信息',
    typeLine: '叙事视角不统一',
    trainingLine: '写了当前视角角色不可能知道的信息，读者失去"谁在看"的确定感',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T012'],
    actions: ['A002'],
  ),
  SyndromeRecord(
    id: 'P006',
    name: '节奏停滞',
    shortName: '节奏停滞',
    keyword: '叙事停滞无推进',
    oneLine: '连续多段无新事件/新冲突/新信息，故事原地打转',
    typeLine: '叙事推进过慢',
    trainingLine: '事件推进密度低，叙事静止，读者在想"然后呢"',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.structure,
    position: 'middle',
    techniques: ['T008', 'T017', 'T018', 'T022'],
    actions: ['A003', 'A005', 'A009'],
  ),
  SyndromeRecord(
    id: 'P007',
    name: '句式节奏单一',
    shortName: '句式节奏单一',
    keyword: '句式结构重复',
    oneLine: '连续多句相同句式结构，缺乏长短/节奏变化',
    typeLine: '句式缺乏变化',
    trainingLine: '连续多句相同结构，读者在句法层面产生疲劳',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l1,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T019', 'T023', 'T025'],
    actions: ['A009', 'A003'],
    v2ActionName: '句式单一',
  ),
  SyndromeRecord(
    id: 'P008',
    name: '语言堆砌',
    shortName: '语言堆砌',
    keyword: '描写密度过高',
    oneLine: '修饰词堆砌，有效信息被稀释，读者费力抓核心',
    typeLine: '表达缺乏效率',
    trainingLine: '描写密度超过叙事所需，核心信息被华丽辞藻稀释',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l1,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T003', 'T002', 'T021', 'T031'],
    actions: ['A006', 'A011', 'A016'],
  ),
  SyndromeRecord(
    id: 'P009',
    name: '角色空心化（含原 P002 角色工具化症状）',
    shortName: '角色空心化',
    keyword: '角色无驱动力',
    oneLine: '角色行为缺乏动机，换角色剧情依然成立',
    typeLine: '角色缺乏行为驱动力',
    trainingLine: '角色缺乏行为驱动力，动机不足、角色被工具化',
    type: SyndromeType.motivationDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T009', 'T004', 'T005'],
    actions: ['A003', 'A007'],
    v1ActionName: '角色空心化（含原 P002 子症状）',
  ),
  SyndromeRecord(
    id: 'P010',
    name: 'OC 平面化',
    shortName: 'OC 平面化',
    keyword: '角色无辨识度',
    oneLine: '角色缺乏独特特征，对话/行为可互换',
    typeLine: '角色缺乏立体感',
    trainingLine: '角色像模板人物，除外表外说不出"只有ta才会做的事"',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T006', 'T007'],
    actions: ['A003', 'A010'],
    v2ActionName: 'OC平面化',
  ),
  SyndromeRecord(
    id: 'P011',
    name: '对话疲劳症',
    shortName: '对话疲劳症',
    keyword: '对话无区分度',
    oneLine: '对话占过多篇幅且无潜台词、无动作支撑',
    typeLine: '对话缺乏表现力',
    trainingLine: '对话占过多篇幅且无区分度、无潜台词、无动作支撑',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l1,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T013', 'T014', 'T015', 'T016'],
    actions: ['A008', 'A006'],
  ),
  // ── L4 情节结构 ──────────────────────────────────────────
  SyndromeRecord(
    id: 'P012',
    name: '张力不足症',
    shortName: '张力不足症',
    keyword: '冲突无分量',
    oneLine: '主角不会输/无代价/无后果，读者不紧张',
    typeLine: '冲突缺乏分量',
    trainingLine: '冲突没有分量与代价，读者知道主角一定会赢',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T017'],
    actions: ['A007', 'A003'],
    v2ActionName: '张力不足',
  ),
  SyndromeRecord(
    id: 'P013',
    name: '开篇平庸症',
    shortName: '开篇平庸症',
    keyword: '开篇无钩子',
    oneLine: '前300字无冲突/悬念/反常，读者3秒内流失',
    typeLine: '开篇缺乏钩子',
    trainingLine: '前300字无冲突/悬念/反常，读者3秒内没有读下去的理由',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'beginning',
    techniques: ['T024'],
    actions: ['A007', 'A001'],
    v2ActionName: '开篇平庸',
  ),
  SyndromeRecord(
    id: 'P014',
    name: '结尾乏力症',
    shortName: '结尾乏力症',
    keyword: '结尾仓促/烂尾',
    oneLine: '收束无满足感，机械降神或伏笔不回收',
    typeLine: '结尾缺少收束满足感',
    trainingLine: '收束仓促或机械降神，读者没有满足感',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'end',
    techniques: ['T025', 'T026'],
    actions: ['A007', 'A003'],
    v2ActionName: '结尾乏力',
  ),
  SyndromeRecord(
    id: 'P015',
    name: '高潮疲软症',
    shortName: '高潮疲软症',
    keyword: '高潮执行不到位',
    oneLine: '铺垫做好了但高潮段落无冲击力',
    typeLine: '高潮执行不到位',
    trainingLine: '铺垫做好了但高潮段落本身没有执行到位',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'middle',
    techniques: ['T027', 'T018'],
    actions: ['A007', 'A009'],
    v2ActionName: '高潮疲软',
  ),
];
