// ─────────────────────────────────────────────────────────────
// syndrome_registry 数据分片：syndrome_registry_p2.dart（R-019 ≤300 行）
// 逐字迁移自 syndrome_registry.dart，零行为变更。
// ─────────────────────────────────────────────────────────────
part of 'syndrome_registry.dart';

/// kSyndromeRegistry 数据段（P016-P031，13 条）
const List<SyndromeRecord> _syndromeRegistryP2 = [
  SyndromeRecord(
    id: 'P016',
    name: '情节巧合过多症',
    shortName: '情节巧合过多症',
    keyword: '情节依赖巧合',
    oneLine: '推进靠偶然事件而非角色主动选择',
    typeLine: '情节驱动依赖巧合',
    trainingLine: '情节推动依赖巧合而非角色主动选择',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T008', 'T009', 'T028'],
    actions: ['A013', 'A003'],
    v2ActionName: '情节巧合过多',
  ),
  SyndromeRecord(
    id: 'P017',
    name: '伏笔失效症',
    shortName: '伏笔失效症',
    keyword: '伏笔埋设/回收问题',
    oneLine: '伏笔裸露/烂尾/解释式回收',
    typeLine: '伏笔埋设/回收有问题',
    trainingLine: '伏笔埋设/铺陈/回收至少一个环节出问题',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T026', 'T017'],
    actions: ['A012', 'A003'],
    v2ActionName: '伏笔失效',
  ),
  // ── L3 角色塑造 ──────────────────────────────────────────
  SyndromeRecord(
    id: 'P018',
    name: '人设崩塌症',
    shortName: '人设崩塌症',
    keyword: '角色中途崩坏',
    oneLine: '连载中角色行为偏离前期建立的模式',
    typeLine: '角色在连载中期崩坏',
    trainingLine: '角色连载中途行为未经铺垫地偏离前期形象',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T030', 'T009'],
    actions: ['A015', 'A010'],
    v2ActionName: '人设崩塌',
  ),
  SyndromeRecord(
    id: 'P019',
    name: '情感失真症',
    shortName: '情感失真症',
    keyword: '情感反应不真实',
    oneLine: '角色情感与情境不匹配，像开关切换',
    typeLine: '情感反应不真实',
    trainingLine: '角色情感反应不符合正常人逻辑，读者无法共情',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T001', 'T020'],
    actions: ['A014', 'A004'],
    v2ActionName: '情感失真',
  ),
  // ── L2 叙事节奏 ──────────────────────────────────────────
  SyndromeRecord(
    id: 'P020',
    name: '过渡生硬症',
    shortName: '过渡生硬症',
    keyword: '场景切换生硬',
    oneLine: '过渡靠"镜头一转"，无感官/情绪连接',
    typeLine: '场景衔接不流畅',
    trainingLine: '场景衔接缺乏流畅感，切换产生断裂',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T029', 'T022'],
    actions: ['A009', 'A006'],
    v2ActionName: '过渡生硬',
  ),
  SyndromeRecord(
    id: 'P021',
    name: '跳跃叙事/过度概括症',
    shortName: '跳跃叙事/过度概括症',
    keyword: '关键事件被概括',
    oneLine: '重要时刻被一两句带过，读者来不及感受',
    typeLine: '情节推进过快，关键事件被概括',
    trainingLine: '关键情节/情绪转折被过度概括，读者来不及"看见"和"感受"',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'global',
    techniques: ['T022', 'T008'],
    actions: ['A009', 'A005'],
    v2ActionName: '跳跃叙事',
  ),
  SyndromeRecord(
    id: 'P022',
    name: '重复用词/基础语病',
    shortName: '重复用词/基础语病',
    keyword: '重复用词/基础语病',
    oneLine: '相邻字重复/连续标点/高频词反复，基础文法问题',
    typeLine: '表达不够精炼',
    trainingLine: '相邻字重复/连续标点/高频词反复，基础文法问题分散注意力',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l1,
    group: MaxAttemptsGroup.expression,
    position: 'local',
    techniques: ['T019', 'T003'],
    actions: ['A016', 'A011'],
  ),
  // ── 批次15（D9 网文商业优先）：P023-P027 ────────────────
  SyndromeRecord(
    id: 'P023',
    name: '爽点乏力症',
    shortName: '爽点乏力症',
    keyword: '爽点乏力',
    oneLine: '关键胜利/优势展示无情绪回报，读者不"爽"',
    typeLine: '情绪回报机制缺失，读者不"爽"',
    trainingLine: '关键胜利/优势展示无情绪回报，读者不"爽"',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'chapter',
    techniques: ['T027', 'T018'],
    actions: ['A005', 'A013'],
  ),
  SyndromeRecord(
    id: 'P024',
    name: '期待感断裂症',
    shortName: '期待感断裂症',
    keyword: '期待感断裂',
    oneLine: '章末钩子不兑现/提前剧透，读者期待落空',
    typeLine: '悬念/承诺管理失衡，期待落空',
    trainingLine: '章末钩子不兑现/提前剧透，读者期待落空',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T017', 'T026'],
    actions: ['A012', 'A003'],
  ),
  SyndromeRecord(
    id: 'P025',
    name: '黄金三章失效症',
    shortName: '黄金三章失效症',
    keyword: '黄金三章失效',
    oneLine: '前三章未建立代入/冲突/金手指/目标，读者流失',
    typeLine: '开篇阅读契约未建立，读者流失',
    trainingLine: '前三章未建立代入/冲突/金手指/目标，读者流失',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T024'],
    actions: ['A007', 'A001'],
  ),
  SyndromeRecord(
    id: 'P026',
    name: '章节钩子缺失症',
    shortName: '章节钩子缺失症',
    keyword: '章节钩子缺失',
    oneLine: '章末无悬念/反转/冲击，无翻页动力',
    typeLine: '章末悬念设计缺失，无翻页动力',
    trainingLine: '章末无悬念/反转/冲击，无翻页动力',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'chapter',
    techniques: ['T017', 'T027'],
    actions: ['A012', 'A009'],
  ),
  SyndromeRecord(
    id: 'P027',
    name: '追读动力不足症',
    shortName: '追读动力不足症',
    keyword: '追读动力不足',
    oneLine: '长线悬念/情感绑定/主线牵引弱，连载中弃书',
    typeLine: '长线留存结构缺失，连载中弃书',
    trainingLine: '长线悬念/情感绑定/主线牵引弱，连载中弃书',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T026', 'T017'],
    actions: ['A013', 'A012'],
  ),
  // ── 批次23-26（叙事基础空缺）：P028-P031 ────────────────
  SyndromeRecord(
    id: 'P028',
    name: '画面感缺失症',
    shortName: '画面感缺失症',
    keyword: '画面感缺失',
    oneLine: '通篇抽象概述无场景化呈现，读者无法脑内成像',
    typeLine: '通篇抽象概述，缺乏场景化呈现',
    trainingLine: '通篇抽象概述无场景化呈现，读者无法脑内成像',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'chapter',
    techniques: ['T001', 'T002'],
    actions: ['A006', 'A004'],
  ),
];
