// ─────────────────────────────────────────────────────────────
// syndrome_registry 数据分片：syndrome_registry_p3.dart（R-019 ≤300 行）
// 逐字迁移自 syndrome_registry.dart，零行为变更。
// ─────────────────────────────────────────────────────────────
part of 'syndrome_registry.dart';

/// kSyndromeRegistry 数据段（P032-P041，13 条）
const List<SyndromeRecord> _syndromeRegistryP3 = [
  SyndromeRecord(
    id: 'P029',
    name: '段落失控症',
    shortName: '段落失控症',
    keyword: '段落失控',
    oneLine: '段落过长无呼吸感或碎片化断行，阅读节奏失衡',
    typeLine: '段落组织失衡，阅读节奏被破坏',
    trainingLine: '段落过长无呼吸感或碎片化断行，阅读节奏失衡',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'chapter',
    techniques: ['T021', 'T019'],
    actions: ['A011', 'A009'],
  ),
  SyndromeRecord(
    id: 'P030',
    name: '节奏比例失衡症',
    shortName: '节奏比例失衡症',
    keyword: '节奏比例失衡',
    oneLine: '铺垫/高潮/收束比例失衡，该快的慢、该慢的快',
    typeLine: '铺垫/高潮/收束比例失衡，节奏错配',
    trainingLine: '铺垫/高潮/收束比例失衡，该快的慢、该慢的快',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T027', 'T025'],
    actions: ['A009', 'A013'],
  ),
  SyndromeRecord(
    id: 'P031',
    name: '设定矛盾症',
    shortName: '设定矛盾症',
    keyword: '设定矛盾',
    oneLine: '世界观设定前后冲突，规则/时间线/能力不自洽',
    typeLine: '世界观设定前后冲突，规则/时间线不自洽',
    trainingLine: '世界观设定前后冲突，规则/时间线/能力不自洽',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'global',
    techniques: ['T017', 'T026'],
    actions: ['A013', 'A012'],
  ),
  // ── 批次32（b10 三症候扩容：网文商业）：P032 ───────────────
  SyndromeRecord(
    id: 'P032',
    name: '金手指失衡症',
    shortName: '金手指失衡症',
    keyword: '金手指使用失衡',
    oneLine: '金手指迟迟不亮相/过强消灭冲突/规则前后崩坏，读者失去代入与期待',
    typeLine: '金手指设定或使用失衡，机制压过叙事',
    trainingLine: '金手指设定与使用失衡——亮相时机、强度上限、规则一致性至少一处出问题',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T017', 'T024', 'T026'],
    actions: ['A013', 'A009'],
  ),
  // ── 批次33（b10 三症候扩容：网文商业）：P033 ───────────────
  SyndromeRecord(
    id: 'P033',
    name: '升级节奏失衡症',
    shortName: '升级节奏失衡症',
    keyword: '升级节奏失衡',
    oneLine: '升级过快力量通货膨胀，或过慢读者失去期待，成长弧线失衡',
    typeLine: '成长/升级节奏失衡，积累感与期待感被破坏',
    trainingLine: '升级节奏失衡——过快导致力量通货膨胀，过慢导致读者失去期待',
    type: SyndromeType.commercialAppeal,
    level: SkillLevel.l4,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T027', 'T008', 'T017'],
    actions: ['A009', 'A013'],
  ),
  // ── 批次34（b10 三症候扩容：配角群像）：P034 ───────────────
  SyndromeRecord(
    id: 'P034',
    name: '配角工具人症',
    shortName: '配角工具人症',
    keyword: '配角功能性过强',
    oneLine: '配角无独立性格/动机/记忆点，仅传话推剧情喊口号',
    typeLine: '配角群像工具化，缺乏独立辨识度',
    trainingLine: '配角仅为剧情服务——无独立动机、无辨识行为、无记忆点',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T006', 'T007', 'T004', 'T005'],
    actions: ['A010', 'A003'],
  ),
  // ── 批次40（b12 四症候扩容：叙事效率与结构硬伤）：P035 ──
  SyndromeRecord(
    id: 'P035',
    name: '对话注水症',
    shortName: '对话注水症',
    keyword: '对话信息冗余',
    oneLine: '对话大量寒暄客套/重复确认/无信息增量，看似推进实则灌水',
    typeLine: '对话叙事效率低，信息密度不足',
    trainingLine: '对话段落信息增量低——寒暄、客套、重复确认、明知故问，不推进剧情不升级矛盾',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.structure,
    position: 'chapter',
    techniques: ['T013', 'T008', 'T016'],
    actions: ['A008', 'A009'],
  ),
  // ── 批次41（b12 四症候扩容：叙事效率与结构硬伤）：P036 ──
  SyndromeRecord(
    id: 'P036',
    name: '流水账叙述症',
    shortName: '流水账叙述症',
    keyword: '事件平铺无聚焦',
    oneLine: '按时间顺序平均罗列事件，无冲突聚焦与轻重缓急，像流水账',
    typeLine: '事件组织缺乏戏剧化结构，平铺直叙',
    trainingLine: '事件按时间平铺直叙，无冲突聚焦与详略分配，读者读不出重点',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'chapter',
    techniques: ['T022', 'T008', 'T018'],
    actions: ['A009', 'A011'],
  ),
  // ── 批次42（b12 四症候扩容：叙事效率与结构硬伤）：P037 ──
  SyndromeRecord(
    id: 'P037',
    name: '心理内耗症',
    shortName: '心理内耗症',
    keyword: '心理独白失控',
    oneLine: '角色内心反复纠结/自我怀疑/复盘过往，大段独白无进展',
    typeLine: '心理描写失控，无进展内耗',
    trainingLine: '心理独白篇幅失控——反复纠结、自我怀疑、复盘过往，无进展内耗稀释节奏',
    type: SyndromeType.expressiveDeficit,
    level: SkillLevel.l2,
    group: MaxAttemptsGroup.expression,
    position: 'chapter',
    techniques: ['T001', 'T009', 'T020'],
    actions: ['A011', 'A004'],
  ),
  // ── 批次43（b12 四症候扩容：叙事效率与结构硬伤）：P038 ──
  SyndromeRecord(
    id: 'P038',
    name: '支线涣散症',
    shortName: '支线涣散症',
    keyword: '支线偏离主线',
    oneLine: '支线剧情不服务主线/人设/爽点，被带跑后主线被搁置',
    typeLine: '支线意义缺失，主线牵引弱化',
    trainingLine: '支线缺乏存在意义——不推动主线、不丰富人设、不提供爽点，主线被搁置',
    type: SyndromeType.structuralDisorder,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.structure,
    position: 'serial',
    techniques: ['T008', 'T017', 'T022'],
    actions: ['A013', 'A002'],
  ),
  // ── 批次45（b13 角色驱动层扩容）：P039 ──
  SyndromeRecord(
    id: 'P039',
    name: '目标模糊症',
    shortName: '目标模糊症',
    keyword: '主角目标不具体',
    oneLine: '主角目标抽象模糊（想变强/要复仇），无数量/期限/代价，读者无可期待',
    typeLine: '角色驱动力不清晰，目标不可追踪',
    trainingLine: '主角欲望缺乏具体化——目标 + 数量 + 截止时间 + 失败代价至少缺两项，读者找不到可「替他着急」的点',
    type: SyndromeType.motivationDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T009', 'T004', 'T005'],
    actions: ['A003', 'A007'],
  ),
  // ── 批次46（b13 角色驱动层扩容）：P040 ──
  SyndromeRecord(
    id: 'P040',
    name: '被动主角症',
    shortName: '被动主角症',
    keyword: '主角无主动性',
    oneLine: '主角被剧情拖着走，无主动决策/权衡/反制，读者一眼出戏',
    typeLine: '主角主动性缺失，决策由剧情代劳',
    trainingLine: '剧情需要主角去哪主角就去哪——无理由、无顾虑、无权衡，角色所有动作必须有动机（内心渴望或外部逼迫）',
    type: SyndromeType.motivationDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T009', 'T005', 'T008'],
    actions: ['A002', 'A007', 'A003'],
  ),
  // ── 批次47（b13 角色驱动层扩容）：P041 ──
  SyndromeRecord(
    id: 'P041',
    name: '降智反派症',
    shortName: '降智反派症',
    keyword: '对手无利益动机',
    oneLine: '反派为坏而坏、降智送人头，无利益动机，冲突失真张力崩坏',
    typeLine: '对手塑造工具化，利益冲突缺席',
    trainingLine: '反派降智——放着自己的资源不用非要无脑死磕，高手博弈只为利益与活路，利益冲突到位矛盾自然爆发',
    type: SyndromeType.motivationDeficit,
    level: SkillLevel.l3,
    group: MaxAttemptsGroup.deep,
    position: 'global',
    techniques: ['T007', 'T005', 'T009'],
    actions: ['A003', 'A007'],
  ),
];
